test compile precise-output
set unwind_info=false
target riscv32 has_m

; Count leading zeros
function %clz_i8(i8) -> i8 {
block0(v0: i8):
    v1 = clz v0
    return v1
}

; VCode:
; block0:
;   mv a5,a0
;   clz a0,a5##ty=i8 tmp=a2 step=a3
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a5, a0
;   mv a0, zero
;   addi a3, zero, 8
;   addi a2, zero, 1
;   slli a2, a2, 7
;   blez a3, 0x1c
;   and t5, a2, a5
;   bne zero, t5, 0x14
;   addi a0, a0, 1
;   addi a3, a3, -1
;   srli a2, a2, 1
;   j -0x18
;   ret

function %clz_i16(i16) -> i16 {
block0(v0: i16):
    v1 = clz v0
    return v1
}

; VCode:
; block0:
;   mv a5,a0
;   clz a0,a5##ty=i16 tmp=a2 step=a3
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a5, a0
;   mv a0, zero
;   addi a3, zero, 0x10
;   addi a2, zero, 1
;   slli a2, a2, 0xf
;   blez a3, 0x1c
;   and t5, a2, a5
;   bne zero, t5, 0x14
;   addi a0, a0, 1
;   addi a3, a3, -1
;   srli a2, a2, 1
;   j -0x18
;   ret

function %clz_i32(i32) -> i32 {
block0(v0: i32):
    v1 = clz v0
    return v1
}

; VCode:
; block0:
;   mv a5,a0
;   clz a0,a5##ty=i32 tmp=a2 step=a3
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a5, a0
;   mv a0, zero
;   addi a3, zero, 0x20
;   addi a2, zero, 1
;   slli a2, a2, 0x1f
;   blez a3, 0x1c
;   and t5, a2, a5
;   bne zero, t5, 0x14
;   addi a0, a0, 1
;   addi a3, a3, -1
;   srli a2, a2, 1
;   j -0x18
;   ret

function %ctz_i8(i8) -> i8 {
block0(v0: i8):
    v1 = ctz v0
    return v1
}

; VCode:
; block0:
;   mv a5,a0
;   ctz a0,a5##ty=i8 tmp=a2 step=a3
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a5, a0
;   mv a0, zero
;   addi a3, zero, 8
;   addi a2, zero, 1
;   blez a3, 0x1c
;   and t5, a2, a5
;   bne zero, t5, 0x14
;   addi a0, a0, 1
;   addi a3, a3, -1
;   slli a2, a2, 1
;   j -0x18
;   ret

function %ctz_i16(i16) -> i16 {
block0(v0: i16):
    v1 = ctz v0
    return v1
}

; VCode:
; block0:
;   mv a5,a0
;   ctz a0,a5##ty=i16 tmp=a2 step=a3
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a5, a0
;   mv a0, zero
;   addi a3, zero, 0x10
;   addi a2, zero, 1
;   blez a3, 0x1c
;   and t5, a2, a5
;   bne zero, t5, 0x14
;   addi a0, a0, 1
;   addi a3, a3, -1
;   slli a2, a2, 1
;   j -0x18
;   ret

function %ctz_i32(i32) -> i32 {
block0(v0: i32):
    v1 = ctz v0
    return v1
}

; VCode:
; block0:
;   mv a5,a0
;   ctz a0,a5##ty=i32 tmp=a2 step=a3
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a5, a0
;   mv a0, zero
;   addi a3, zero, 0x20
;   addi a2, zero, 1
;   blez a3, 0x1c
;   and t5, a2, a5
;   bne zero, t5, 0x14
;   addi a0, a0, 1
;   addi a3, a3, -1
;   slli a2, a2, 1
;   j -0x18
;   ret

function %popcnt_i8(i8) -> i8 {
block0(v0: i8):
    v1 = popcnt v0
    return v1
}

; VCode:
; block0:
;   andi a2,a0,255
;   popcnt a0,a2##ty=i64 tmp=a4 step=a5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a2, a0, 0xff
;   mv a0, zero
;   addi a5, zero, 0x40
;   addi a4, zero, 1
;   slli a4, a4, 0x3f
;   blez a5, 0x1c
;   and t5, a4, a2
;   beq zero, t5, 8
;   addi a0, a0, 1
;   addi a5, a5, -1
;   srli a4, a4, 1
;   j -0x18
;   ret

function %popcnt_i16(i16) -> i16 {
block0(v0: i16):
    v1 = popcnt v0
    return v1
}

; VCode:
; block0:
;   slli a2,a0,48
;   srli a4,a2,48
;   popcnt a0,a4##ty=i64 tmp=a2 step=a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a2, a0, 0x30
;   srli a4, a2, 0x30
;   mv a0, zero
;   addi a1, zero, 0x40
;   addi a2, zero, 1
;   slli a2, a2, 0x3f
;   blez a1, 0x1c
;   and t5, a2, a4
;   beq zero, t5, 8
;   addi a0, a0, 1
;   addi a1, a1, -1
;   srli a2, a2, 1
;   j -0x18
;   ret

function %popcnt_i32(i32) -> i32 {
block0(v0: i32):
    v1 = popcnt v0
    return v1
}

; VCode:
; block0:
;   slli a2,a0,32
;   srli a4,a2,32
;   popcnt a0,a4##ty=i64 tmp=a2 step=a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a2, a0, 0x20
;   srli a4, a2, 0x20
;   mv a0, zero
;   addi a1, zero, 0x40
;   addi a2, zero, 1
;   slli a2, a2, 0x3f
;   blez a1, 0x1c
;   and t5, a2, a4
;   beq zero, t5, 8
;   addi a0, a0, 1
;   addi a1, a1, -1
;   srli a2, a2, 1
;   j -0x18
;   ret

function %bnot_i32(i32) -> i32 {
block0(v0: i32):
    v1 = bnot v0
    return v1
}

; VCode:
; block0:
;   not a0,a0
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   not a0, a0
;   ret

function %band_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = band v0, v1
    return v2
}

; VCode:
; block0:
;   and a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   and a0, a0, a1
;   ret

function %band_i32_constant(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 3
    v2 = band v0, v1
    return v2
}

; VCode:
; block0:
;   andi a0,a0,3
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a0, a0, 3
;   ret

function %band_i32_constant_shift(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = iconst.i32 3
    v3 = ishl.i32 v1, v2
    v4 = band v0, v3
    return v4
}

; VCode:
; block0:
;   slli a4,a1,3
;   and a0,a0,a4
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a4, a1, 3
;   and a0, a0, a4
;   ret

function %bor_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = bor v0, v1
    return v2
}

; VCode:
; block0:
;   or a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   or a0, a0, a1
;   ret

function %bor_i32_constant(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 3
    v2 = bor v0, v1
    return v2
}

; VCode:
; block0:
;   ori a0,a0,3
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   ori a0, a0, 3
;   ret

function %bor_i32_constant_shift(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = iconst.i32 3
    v3 = ishl.i32 v1, v2
    v4 = bor v0, v3
    return v4
}

; VCode:
; block0:
;   slli a4,a1,3
;   or a0,a0,a4
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a4, a1, 3
;   or a0, a0, a4
;   ret

function %bxor_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = bxor v0, v1
    return v2
}

; VCode:
; block0:
;   xor a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   xor a0, a0, a1
;   ret

function %bxor_i32_constant(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 3
    v2 = bxor v0, v1
    return v2
}

; VCode:
; block0:
;   xori a0,a0,3
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   xori a0, a0, 3
;   ret

function %bxor_i32_constant_shift(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = iconst.i32 3
    v3 = ishl.i32 v1, v2
    v4 = bxor v0, v3
    return v4
}

; VCode:
; block0:
;   slli a4,a1,3
;   xor a0,a0,a4
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a4, a1, 3
;   xor a0, a0, a4
;   ret

function %band_not_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = band_not v0, v1
    return v2
}

; VCode:
; block0:
;   not a4,a1
;   and a0,a0,a4
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   not a4, a1
;   and a0, a0, a4
;   ret

function %band_not_i32_constant(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 4
    v2 = band_not v0, v1
    return v2
}

; VCode:
; block0:
;   li a4,4
;   not a4,a4
;   and a0,a0,a4
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi a4, zero, 4
;   not a4, a4
;   and a0, a0, a4
;   ret

function %bor_not_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = bor_not v0, v1
    return v2
}

; VCode:
; block0:
;   not a4,a1
;   or a0,a0,a4
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   not a4, a1
;   or a0, a0, a4
;   ret

function %bxor_not_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = bxor_not v0, v1
    return v2
}

; VCode:
; block0:
;   not a4,a1
;   xor a0,a0,a4
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   not a4, a1
;   xor a0, a0, a4
;   ret

;;;; i64 tests (2-register pattern on RV32)

function %clz_i64(i64) -> i64 {
block0(v0: i64):
    v1 = clz v0
    return v1
}

; VCode:
; block0:
;   clz a5,a1##ty=i64 tmp=a3 step=a4
;   clz a3,a0##ty=i64 tmp=a4 step=a2
;   select a0,a3,zero##condition=(a1 eq zero)
;   add a0,a5,a0
;   li a1,0
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a5, zero
;   addi a4, zero, 0x40
;   addi a3, zero, 1
;   slli a3, a3, 0x3f
;   blez a4, 0x1c
;   and t5, a3, a1
;   bne zero, t5, 0x14
;   addi a5, a5, 1
;   addi a4, a4, -1
;   srli a3, a3, 1
;   j -0x18
;   mv a3, zero
;   addi a2, zero, 0x40
;   addi a4, zero, 1
;   slli a4, a4, 0x3f
;   blez a2, 0x1c
;   and t5, a4, a0
;   bne zero, t5, 0x14
;   addi a3, a3, 1
;   addi a2, a2, -1
;   srli a4, a4, 1
;   j -0x18
;   mv a0, a3
;   beqz a1, 8
;   mv a0, zero
;   add a0, a5, a0
;   mv a1, zero
;   ret

function %ctz_i64(i64) -> i64 {
block0(v0: i64):
    v1 = ctz v0
    return v1
}

; VCode:
; block0:
;   ctz a5,a1##ty=i32 tmp=a3 step=a4
;   ctz a3,a0##ty=i32 tmp=a1 step=a2
;   select a5,a5,zero##condition=(a0 eq zero)
;   add a0,a3,a5
;   li a1,0
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a5, zero
;   addi a4, zero, 0x20
;   addi a3, zero, 1
;   blez a4, 0x1c
;   and t5, a3, a1
;   bne zero, t5, 0x14
;   addi a5, a5, 1
;   addi a4, a4, -1
;   slli a3, a3, 1
;   j -0x18
;   mv a3, zero
;   addi a2, zero, 0x20
;   addi a1, zero, 1
;   blez a2, 0x1c
;   and t5, a1, a0
;   bne zero, t5, 0x14
;   addi a3, a3, 1
;   addi a2, a2, -1
;   slli a1, a1, 1
;   j -0x18
;   beqz a0, 8
;   mv a5, zero
;   add a0, a3, a5
;   mv a1, zero
;   ret

function %cls_i64(i64) -> i64 {
block0(v0: i64):
    v1 = cls v0
    return v1
}

; VCode:
; block0:
;   not a3,a0
;   select a5,a3,a0##condition=(a1 slt zero)
;   not a2,a1
;   select a3,a2,a1##condition=(a1 slt zero)
;   clz a1,a3##ty=i64 tmp=a2 step=a0
;   clz a0,a5##ty=i64 tmp=a2 step=a4
;   select a2,a0,zero##condition=(a3 eq zero)
;   add a3,a1,a2
;   addi a0,a3,-1
;   li a1,0
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   not a3, a0
;   mv a5, a3
;   bltz a1, 8
;   mv a5, a0
;   not a2, a1
;   mv a3, a2
;   bltz a1, 8
;   mv a3, a1
;   mv a1, zero
;   addi a0, zero, 0x40
;   addi a2, zero, 1
;   slli a2, a2, 0x3f
;   blez a0, 0x1c
;   and t5, a2, a3
;   bne zero, t5, 0x14
;   addi a1, a1, 1
;   addi a0, a0, -1
;   srli a2, a2, 1
;   j -0x18
;   mv a0, zero
;   addi a4, zero, 0x40
;   addi a2, zero, 1
;   slli a2, a2, 0x3f
;   blez a4, 0x1c
;   and t5, a2, a5
;   bne zero, t5, 0x14
;   addi a0, a0, 1
;   addi a4, a4, -1
;   srli a2, a2, 1
;   j -0x18
;   mv a2, a0
;   beqz a3, 8
;   mv a2, zero
;   add a3, a1, a2
;   addi a0, a3, -1
;   mv a1, zero
;   ret

function %popcnt_i64(i64) -> i64 {
block0(v0: i64):
    v1 = popcnt v0
    return v1
}

function %bnot_i64(i64) -> i64 {
block0(v0: i64):
    v1 = bnot v0
    return v1
}

function %band_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = band v0, v1
    return v2
}

function %bor_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = bor v0, v1
    return v2
}

function %bxor_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = bxor v0, v1
    return v2
}

function %band_not_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = band_not v0, v1
    return v2
}

function %bor_not_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = bor_not v0, v1
    return v2
}

function %bxor_not_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = bxor_not v0, v1
    return v2
}

