test compile precise-output
set unwind_info=false
target riscv32 has_m

function %bswap_i16(i16) -> i16 {
block0(v0: i16):
    v1 = bswap v0
    return v1
}

; VCode:
; block0:
;   slli a2,a0,8
;   srli a4,a0,8
;   slli a0,a4,56
;   srli a3,a0,56
;   or a0,a2,a3
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a2, a0, 8
;   srli a4, a0, 8
;   slli a0, a4, 0x38
;   srli a3, a0, 0x38
;   or a0, a2, a3
;   ret

function %bswap_i32(i32) -> i32 {
block0(v0: i32):
    v1 = bswap v0
    return v1
}

; VCode:
; block0:
;   slli a2,a0,8
;   srli a4,a0,8
;   slli a1,a4,56
;   srli a3,a1,56
;   or a4,a2,a3
;   slli a1,a4,16
;   srli a2,a0,16
;   slli a4,a2,8
;   srli a0,a2,8
;   slli a2,a0,56
;   srli a5,a2,56
;   or a0,a4,a5
;   slli a2,a0,48
;   srli a4,a2,48
;   or a0,a1,a4
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a2, a0, 8
;   srli a4, a0, 8
;   slli a1, a4, 0x38
;   srli a3, a1, 0x38
;   or a4, a2, a3
;   slli a1, a4, 0x10
;   srli a2, a0, 0x10
;   slli a4, a2, 8
;   srli a0, a2, 8
;   slli a2, a0, 0x38
;   srli a5, a2, 0x38
;   or a0, a4, a5
;   slli a2, a0, 0x30
;   srli a4, a2, 0x30
;   or a0, a1, a4
;   ret

;;;; i64 tests (2-register pattern on RV32)

function %bswap_i64(i64) -> i64 {
block0(v0: i64):
    v1 = bswap v0
    return v1
}

