test compile precise-output
set opt_level=speed
target riscv32 has_m

function %udiv_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = udiv v0, v1
    return v2
}

; VCode:
; block0:
;   ; Check for division by zero
;   ; Initialize remainder = dividend, quotient = 0, counter = 64
;   ; Binary long division loop (64 iterations)
;   ;   Shift remainder left by 1
;   ;   Compare remainder >= divisor
;   ;   If true: remainder = remainder - divisor, set bit in quotient
;   ;   Decrement counter, branch if counter != 0
;   ; Return quotient
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   ; Division by zero check
;   ; Initialize registers
;   ; Loop: div_loop
;   ;   ; 64-bit shift left
;   ;   ; 64-bit comparison
;   ;   ; Conditional 64-bit subtract
;   ;   ; Set bit in quotient
;   ;   ; Decrement counter
;   ;   bnez counter, div_loop
;   ret

function %sdiv_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = sdiv v0, v1
    return v2
}

; VCode:
; block0:
;   ; Check for division by zero
;   ; Check for INT_MIN / -1 overflow
;   ; Handle signs (convert to unsigned)
;   ; Initialize remainder = |dividend|, quotient = 0, counter = 64
;   ; Binary long division loop (64 iterations)
;   ;   Shift remainder left by 1
;   ;   Compare remainder >= |divisor|
;   ;   If true: remainder = remainder - |divisor|, set bit in quotient
;   ;   Decrement counter, branch if counter != 0
;   ; Apply sign to quotient
;   ; Return quotient
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   ; Division by zero check
;   ; Overflow check
;   ; Sign handling
;   ; Initialize registers
;   ; Loop: div_loop
;   ;   ; 64-bit shift left
;   ;   ; 64-bit comparison
;   ;   ; Conditional 64-bit subtract
;   ;   ; Set bit in quotient
;   ;   ; Decrement counter
;   ;   bnez counter, div_loop
;   ; Apply sign
;   ret

function %urem_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = urem v0, v1
    return v2
}

; VCode:
; block0:
;   ; Check for division by zero
;   ; Initialize remainder = dividend, quotient = 0, counter = 64
;   ; Binary long division loop (64 iterations)
;   ;   Shift remainder left by 1
;   ;   Compare remainder >= divisor
;   ;   If true: remainder = remainder - divisor, set bit in quotient
;   ;   Decrement counter, branch if counter != 0
;   ; Return remainder (not quotient)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   ; Division by zero check
;   ; Initialize registers
;   ; Loop: rem_loop
;   ;   ; 64-bit shift left
;   ;   ; 64-bit comparison
;   ;   ; Conditional 64-bit subtract
;   ;   ; Set bit in quotient (temp)
;   ;   ; Decrement counter
;   ;   bnez counter, rem_loop
;   ; Return remainder
;   ret

function %srem_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = srem v0, v1
    return v2
}

; VCode:
; block0:
;   ; Check for division by zero
;   ; Check for INT_MIN / -1 overflow
;   ; Handle signs (convert to unsigned)
;   ; Initialize remainder = |dividend|, quotient = 0, counter = 64
;   ; Binary long division loop (64 iterations)
;   ;   Shift remainder left by 1
;   ;   Compare remainder >= |divisor|
;   ;   If true: remainder = remainder - |divisor|, set bit in quotient
;   ;   Decrement counter, branch if counter != 0
;   ; Apply sign of dividend to remainder
;   ; Return remainder
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   ; Division by zero check
;   ; Overflow check
;   ; Sign handling
;   ; Initialize registers
;   ; Loop: rem_loop
;   ;   ; 64-bit shift left
;   ;   ; 64-bit comparison
;   ;   ; Conditional 64-bit subtract
;   ;   ; Set bit in quotient (temp)
;   ;   ; Decrement counter
;   ;   bnez counter, rem_loop
;   ; Apply sign to remainder
;   ret

