test compile precise-output
target riscv32 has_m

function %iabs_i8(i8) -> i8 {
block0(v0: i8):
    v1 = iabs v0
    return v1
}

; VCode:
; block0:
;   slli a2,a0,56
;   srai a4,a2,56
;   sub a1,zero,a4
;   select a0,a4,a1##condition=(a4 sgt a1)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a2, a0, 0x38
;   srai a4, a2, 0x38
;   neg a1, a4
;   mv a0, a4
;   blt a1, a4, 8
;   mv a0, a1
;   ret

function %iabs_i16(i16) -> i16 {
block0(v0: i16):
    v1 = iabs v0
    return v1
}

; VCode:
; block0:
;   slli a2,a0,48
;   srai a4,a2,48
;   sub a1,zero,a4
;   select a0,a4,a1##condition=(a4 sgt a1)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a2, a0, 0x30
;   srai a4, a2, 0x30
;   neg a1, a4
;   mv a0, a4
;   blt a1, a4, 8
;   mv a0, a1
;   ret

function %iabs_i32(i32) -> i32 {
block0(v0: i32):
    v1 = iabs v0
    return v1
}

; VCode:
; block0:
;   slli a2,a0,32
;   srai a4,a2,32
;   sub a1,zero,a4
;   select a0,a4,a1##condition=(a4 sgt a1)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a2, a0, 0x20
;   srai a4, a2, 0x20
;   neg a1, a4
;   mv a0, a4
;   blt a1, a4, 8
;   mv a0, a1
;   ret

