test compile precise-output
set unwind_info=false
target riscv32 has_m

; ireduce from i32 to smaller types
function %ireduce_i32_i8(i32) -> i8 {
block0(v0: i32):
    v1 = ireduce.i8 v0
    return v1
}

; VCode:
; block0:
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   ret

function %ireduce_i32_i16(i32) -> i16 {
block0(v0: i32):
    v1 = ireduce.i16 v0
    return v1
}

; VCode:
; block0:
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   ret

function %ireduce_i16_i8(i16) -> i8 {
block0(v0: i16):
    v1 = ireduce.i8 v0
    return v1
}

; VCode:
; block0:
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   ret

