test compile precise-output
set unwind_info=false
target riscv32 has_m

function %ishl_i8_i8(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a3,a1,7
;   sll a0,a0,a3
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a3, a1, 7
;   sll a0, a0, a3
;   ret

function %ishl_i16_i16(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a3,a1,15
;   sll a0,a0,a3
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a3, a1, 0xf
;   sll a0, a0, a3
;   ret

function %ishl_i32_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   sll a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sll a0, a0, a1
;   ret

function %ishl_i32_imm(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 17
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   slli a0,a0,17
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a0, a0, 0x11
;   ret

;;;; i64 tests (2-register pattern on RV32)

function %ishl_i64_i8(i64, i8) -> i64 {
block0(v0: i64, v1: i8):
    v2 = ishl v0, v1
    return v2
}

function %ishl_i64_i16(i64, i16) -> i64 {
block0(v0: i64, v1: i16):
    v2 = ishl v0, v1
    return v2
}

function %ishl_i64_i32(i64, i32) -> i64 {
block0(v0: i64, v1: i32):
    v2 = ishl v0, v1
    return v2
}

function %ishl_i64_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = ishl v0, v1
    return v2
}

function %ishl_i64_imm(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 17
    v2 = ishl v0, v1
    return v2
}

function %ishl_i64_imm_32(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 32
    v2 = ishl v0, v1
    return v2
}

function %ishl_i64_imm_63(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 63
    v2 = ishl v0, v1
    return v2
}
