test compile precise-output
set unwind_info=false
target riscv32 has_m

function %rotr_i32_const(i32) -> i32 {
block0(v0: i32):
  v1 = iconst.i32 5
  v2 = rotr.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   li a1,5
;   slli a3,a0,32
;   srli a5,a3,32
;   andi a1,a1,31
;   li a3,32
;   sub a0,a3,a1
;   srl a2,a5,a1
;   sll a3,a5,a0
;   select a5,zero,a3##condition=(a1 eq zero)
;   or a0,a2,a5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi a1, zero, 5
;   slli a3, a0, 0x20
;   srli a5, a3, 0x20
;   andi a1, a1, 0x1f
;   addi a3, zero, 0x20
;   sub a0, a3, a1
;   srl a2, a5, a1
;   sll a3, a5, a0
;   mv a5, zero
;   beqz a1, 8
;   mv a5, a3
;   or a0, a2, a5
;   ret

;;;; i64 tests (2-register pattern on RV32)

function %rotr_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
  v2 = rotr.i64 v0, v1
  return v2
}

function %rotr_i64_const(i64) -> i64 {
block0(v0: i64):
  v1 = iconst.i64 5
  v2 = rotr.i64 v0, v1
  return v2
}

function %rotr_i64_const_i32(i64) -> i64 {
block0(v0: i64):
  v1 = iconst.i32 5
  v2 = rotr.i64 v0, v1
  return v2
}

function %rotr_i64_const_32(i64) -> i64 {
block0(v0: i64):
  v1 = iconst.i64 32
  v2 = rotr.i64 v0, v1
  return v2
}

