test compile precise-output
set unwind_info=false
target riscv32 has_m

function %smax_i8(i8, i8) -> i8{
block0(v0: i8, v1: i8):
    v2 = smax v0, v1
    return v2
}

; VCode:
; block0:
;   slli a3,a0,56
;   srai a5,a3,56
;   slli a1,a1,56
;   srai a3,a1,56
;   select a0,a5,a3##condition=(a5 sgt a3)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a3, a0, 0x38
;   srai a5, a3, 0x38
;   slli a1, a1, 0x38
;   srai a3, a1, 0x38
;   mv a0, a5
;   blt a3, a5, 8
;   mv a0, a3
;   ret

function %smax_i16(i16, i16) -> i16{
block0(v0: i16, v1: i16):
    v2 = smax v0, v1
    return v2
}

; VCode:
; block0:
;   slli a3,a0,48
;   srai a5,a3,48
;   slli a1,a1,48
;   srai a3,a1,48
;   select a0,a5,a3##condition=(a5 sgt a3)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a3, a0, 0x30
;   srai a5, a3, 0x30
;   slli a1, a1, 0x30
;   srai a3, a1, 0x30
;   mv a0, a5
;   blt a3, a5, 8
;   mv a0, a3
;   ret

function %smax_i32(i32, i32) -> i32{
block0(v0: i32, v1: i32):
    v2 = smax v0, v1
    return v2
}

; VCode:
; block0:
;   slli a3,a0,32
;   srai a5,a3,32
;   slli a1,a1,32
;   srai a3,a1,32
;   select a0,a5,a3##condition=(a5 sgt a3)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a3, a0, 0x20
;   srai a5, a3, 0x20
;   slli a1, a1, 0x20
;   srai a3, a1, 0x20
;   mv a0, a5
;   blt a3, a5, 8
;   mv a0, a3
;   ret

