test compile precise-output
set unwind_info=false
target riscv32 has_m

function %sshr_i8_i8(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
    v2 = sshr v0, v1
    return v2
}

; VCode:
; block0:
;   slli a3,a0,56
;   srai a5,a3,56
;   andi a1,a1,7
;   sra a0,a5,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a3, a0, 0x38
;   srai a5, a3, 0x38
;   andi a1, a1, 7
;   sra a0, a5, a1
;   ret

function %sshr_i16_i16(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
    v2 = sshr v0, v1
    return v2
}

; VCode:
; block0:
;   slli a3,a0,48
;   srai a5,a3,48
;   andi a1,a1,15
;   sra a0,a5,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a3, a0, 0x30
;   srai a5, a3, 0x30
;   andi a1, a1, 0xf
;   sra a0, a5, a1
;   ret

function %sshr_i32_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = sshr v0, v1
    return v2
}

; VCode:
; block0:
;   sra a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sra a0, a0, a1
;   ret

function %sshr_i32_imm(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 17
    v2 = sshr v0, v1
    return v2
}

; VCode:
; block0:
;   srai a0,a0,17
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   srai a0, a0, 0x11
;   ret

;;;; i64 tests (2-register pattern on RV32)

function %sshr_i64_i8(i64, i8) -> i64 {
block0(v0: i64, v1: i8):
    v2 = sshr v0, v1
    return v2
}

; VCode:
; block0:
;   andi a4,a2,31
;   li a3,32
;   sub a3,a3,a4
;   sll a5,a1,a3
;   select a3,zero,a5##condition=(a4 eq zero)
;   srl a5,a0,a4
;   or a5,a3,a5
;   li t0,32
;   sra a3,a1,a4
;   andi a4,a2,63
;   srai a2,a1,31
;   select [a0,a1],[a3,a2],[a5,a3]##condition=(a4 uge t0)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a4, a2, 0x1f
;   addi a3, zero, 0x20
;   sub a3, a3, a4
;   sll a5, a1, a3
;   mv a3, zero
;   beqz a4, 8
;   mv a3, a5
;   srl a5, a0, a4
;   or a5, a3, a5
;   addi t0, zero, 0x20
;   sra a3, a1, a4
;   andi a4, a2, 0x3f
;   srai a2, a1, 0x1f
;   mv a0, a3
;   mv a1, a2
;   bgeu a4, t0, 0xc
;   mv a0, a5
;   mv a1, a3
;   ret

function %sshr_i64_i16(i64, i16) -> i64 {
block0(v0: i64, v1: i16):
    v2 = sshr v0, v1
    return v2
}

; VCode:
; block0:
;   andi a4,a2,31
;   li a3,32
;   sub a3,a3,a4
;   sll a5,a1,a3
;   select a3,zero,a5##condition=(a4 eq zero)
;   srl a5,a0,a4
;   or a5,a3,a5
;   li t0,32
;   sra a3,a1,a4
;   andi a4,a2,63
;   srai a2,a1,31
;   select [a0,a1],[a3,a2],[a5,a3]##condition=(a4 uge t0)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a4, a2, 0x1f
;   addi a3, zero, 0x20
;   sub a3, a3, a4
;   sll a5, a1, a3
;   mv a3, zero
;   beqz a4, 8
;   mv a3, a5
;   srl a5, a0, a4
;   or a5, a3, a5
;   addi t0, zero, 0x20
;   sra a3, a1, a4
;   andi a4, a2, 0x3f
;   srai a2, a1, 0x1f
;   mv a0, a3
;   mv a1, a2
;   bgeu a4, t0, 0xc
;   mv a0, a5
;   mv a1, a3
;   ret

function %sshr_i64_i32(i64, i32) -> i64 {
block0(v0: i64, v1: i32):
    v2 = sshr v0, v1
    return v2
}

; VCode:
; block0:
;   andi a4,a2,31
;   li a3,32
;   sub a3,a3,a4
;   sll a5,a1,a3
;   select a3,zero,a5##condition=(a4 eq zero)
;   srl a5,a0,a4
;   or a5,a3,a5
;   li t0,32
;   sra a3,a1,a4
;   andi a4,a2,63
;   srai a2,a1,31
;   select [a0,a1],[a3,a2],[a5,a3]##condition=(a4 uge t0)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a4, a2, 0x1f
;   addi a3, zero, 0x20
;   sub a3, a3, a4
;   sll a5, a1, a3
;   mv a3, zero
;   beqz a4, 8
;   mv a3, a5
;   srl a5, a0, a4
;   or a5, a3, a5
;   addi t0, zero, 0x20
;   sra a3, a1, a4
;   andi a4, a2, 0x3f
;   srai a2, a1, 0x1f
;   mv a0, a3
;   mv a1, a2
;   bgeu a4, t0, 0xc
;   mv a0, a5
;   mv a1, a3
;   ret

function %sshr_i64_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = sshr v0, v1
    return v2
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-16
;   sd s11,8(sp)
; block0:
;   andi a5,a2,31
;   li a3,32
;   sub a3,a3,a5
;   sll a3,a1,a3
;   select a3,zero,a3##condition=(a5 eq zero)
;   srl a4,a0,a5
;   or s11,a3,a4
;   li a3,32
;   sra a4,a1,a5
;   andi a5,a2,63
;   srai a2,a1,31
;   select [a0,a1],[a4,a2],[s11,a4]##condition=(a5 uge a3)
;   ld s11,8(sp)
;   addi sp,sp,16
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x11, 0x00
;   .byte 0x23, 0x30, 0x81, 0x00
;   mv s0, sp
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0xb1, 0x01
; block1: ; offset 0x18
;   andi a5, a2, 0x1f
;   addi a3, zero, 0x20
;   sub a3, a3, a5
;   sll a3, a1, a3
;   bnez a5, 8
;   mv a3, zero
;   srl a4, a0, a5
;   or s11, a3, a4
;   addi a3, zero, 0x20
;   sra a4, a1, a5
;   andi a5, a2, 0x3f
;   srai a2, a1, 0x1f
;   mv a0, a4
;   mv a1, a2
;   bgeu a5, a3, 0xc
;   mv a0, s11
;   mv a1, a4
;   .byte 0x83, 0x3d, 0x81, 0x00
;   addi sp, sp, 0x10
;   .byte 0x83, 0x30, 0x81, 0x00
;   .byte 0x03, 0x34, 0x01, 0x00
;   addi sp, sp, 0x10
;   ret

function %sshr_i64_imm(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 17
    v2 = sshr v0, v1
    return v2
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-16
;   sd s11,8(sp)
; block0:
;   li a4,17
;   li a2,0
;   andi a5,a4,31
;   li a2,32
;   sub a3,a2,a5
;   sll a2,a1,a3
;   select a2,zero,a2##condition=(a5 eq zero)
;   srl a3,a0,a5
;   or s11,a2,a3
;   li a2,32
;   sra a3,a1,a5
;   andi a5,a4,63
;   srai a4,a1,31
;   select [a0,a1],[a3,a4],[s11,a3]##condition=(a5 uge a2)
;   ld s11,8(sp)
;   addi sp,sp,16
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x11, 0x00
;   .byte 0x23, 0x30, 0x81, 0x00
;   mv s0, sp
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0xb1, 0x01
; block1: ; offset 0x18
;   addi a4, zero, 0x11
;   mv a2, zero
;   andi a5, a4, 0x1f
;   addi a2, zero, 0x20
;   sub a3, a2, a5
;   sll a2, a1, a3
;   bnez a5, 8
;   mv a2, zero
;   srl a3, a0, a5
;   or s11, a2, a3
;   addi a2, zero, 0x20
;   sra a3, a1, a5
;   andi a5, a4, 0x3f
;   srai a4, a1, 0x1f
;   mv a0, a3
;   mv a1, a4
;   bgeu a5, a2, 0xc
;   mv a0, s11
;   mv a1, a3
;   .byte 0x83, 0x3d, 0x81, 0x00
;   addi sp, sp, 0x10
;   .byte 0x83, 0x30, 0x81, 0x00
;   .byte 0x03, 0x34, 0x01, 0x00
;   addi sp, sp, 0x10
;   ret

function %sshr_i64_imm_32(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 32
    v2 = sshr v0, v1
    return v2
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-16
;   sd s11,8(sp)
; block0:
;   li a4,32
;   li a2,0
;   andi a5,a4,31
;   li a2,32
;   sub a3,a2,a5
;   sll a2,a1,a3
;   select a2,zero,a2##condition=(a5 eq zero)
;   srl a3,a0,a5
;   or s11,a2,a3
;   li a2,32
;   sra a3,a1,a5
;   andi a5,a4,63
;   srai a4,a1,31
;   select [a0,a1],[a3,a4],[s11,a3]##condition=(a5 uge a2)
;   ld s11,8(sp)
;   addi sp,sp,16
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x11, 0x00
;   .byte 0x23, 0x30, 0x81, 0x00
;   mv s0, sp
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0xb1, 0x01
; block1: ; offset 0x18
;   addi a4, zero, 0x20
;   mv a2, zero
;   andi a5, a4, 0x1f
;   addi a2, zero, 0x20
;   sub a3, a2, a5
;   sll a2, a1, a3
;   bnez a5, 8
;   mv a2, zero
;   srl a3, a0, a5
;   or s11, a2, a3
;   addi a2, zero, 0x20
;   sra a3, a1, a5
;   andi a5, a4, 0x3f
;   srai a4, a1, 0x1f
;   mv a0, a3
;   mv a1, a4
;   bgeu a5, a2, 0xc
;   mv a0, s11
;   mv a1, a3
;   .byte 0x83, 0x3d, 0x81, 0x00
;   addi sp, sp, 0x10
;   .byte 0x83, 0x30, 0x81, 0x00
;   .byte 0x03, 0x34, 0x01, 0x00
;   addi sp, sp, 0x10
;   ret

function %sshr_i64_imm_63(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 63
    v2 = sshr v0, v1
    return v2
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-16
;   sd s11,8(sp)
; block0:
;   li a4,63
;   li a2,0
;   andi a5,a4,31
;   li a2,32
;   sub a3,a2,a5
;   sll a2,a1,a3
;   select a2,zero,a2##condition=(a5 eq zero)
;   srl a3,a0,a5
;   or s11,a2,a3
;   li a2,32
;   sra a3,a1,a5
;   andi a5,a4,63
;   srai a4,a1,31
;   select [a0,a1],[a3,a4],[s11,a3]##condition=(a5 uge a2)
;   ld s11,8(sp)
;   addi sp,sp,16
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x11, 0x00
;   .byte 0x23, 0x30, 0x81, 0x00
;   mv s0, sp
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0xb1, 0x01
; block1: ; offset 0x18
;   addi a4, zero, 0x3f
;   mv a2, zero
;   andi a5, a4, 0x1f
;   addi a2, zero, 0x20
;   sub a3, a2, a5
;   sll a2, a1, a3
;   bnez a5, 8
;   mv a2, zero
;   srl a3, a0, a5
;   or s11, a2, a3
;   addi a2, zero, 0x20
;   sra a3, a1, a5
;   andi a5, a4, 0x3f
;   srai a4, a1, 0x1f
;   mv a0, a3
;   mv a1, a4
;   bgeu a5, a2, 0xc
;   mv a0, s11
;   mv a1, a3
;   .byte 0x83, 0x3d, 0x81, 0x00
;   addi sp, sp, 0x10
;   .byte 0x83, 0x30, 0x81, 0x00
;   .byte 0x03, 0x34, 0x01, 0x00
;   addi sp, sp, 0x10
;   ret

