test compile precise-output
set unwind_info=false
target riscv32 has_m

function %trap_user() {
block0:
  trap user1
}

; VCode:
; block0:
;   udf##trap_code=user1
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x00, 0x00, 0x00, 0x00 ; trap: user1

function %trapnz_i32(i32) {
block0(v0: i32):
  trapnz v0, user1
  return
}

; VCode:
; block0:
;   trap_if user1##(a0 ne zero)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   beqz a0, 8
;   .byte 0x00, 0x00, 0x00, 0x00 ; trap: user1
;   ret

function %trapnz_icmp_fold(i32) {
block0(v0: i32):
  v1 = iconst.i32 42
  v2 = icmp eq v0, v1
  trapnz v2, user1
  return
}

; VCode:
; block0:
;   li a2,42
;   trap_if user1##(a0 eq a2)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi a2, zero, 0x2a
;   bne a0, a2, 8
;   .byte 0x00, 0x00, 0x00, 0x00 ; trap: user1
;   ret

function %trapz_i32(i32) {
block0(v0: i32):
  trapz v0, user1
  return
}

; VCode:
; block0:
;   trap_if user1##(a0 eq zero)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   bnez a0, 8
;   .byte 0x00, 0x00, 0x00, 0x00 ; trap: user1
;   ret

