test compile precise-output
set unwind_info=false
target riscv32 has_m

function %load_base_offset(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = iadd.i32 v0, v1
  v3 = load.i32 v2
  return v3
}

; VCode:
; block0:
;   add a4,a0,a1
;   lw a0,0(a4)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   add a4, a0, a1
;   lw a0, 0(a4) ; trap: heap_oob
;   ret

function %load_with_constant_offset(i32) -> i32 {
block0(v0: i32):
  v1 = load.i32 v0+4
  return v1
}

; VCode:
; block0:
;   lw a0,4(a0)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lw a0, 4(a0) ; trap: heap_oob
;   ret

function %store_base_offset(i32, i32, i32) {
block0(v0: i32, v1: i32, v2: i32):
  v3 = iadd.i32 v0, v1
  store.i32 v2, v3
  return
}

; VCode:
; block0:
;   add a4,a0,a1
;   sw a2,0(a4)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   add a4, a0, a1
;   sw a2, 0(a4) ; trap: heap_oob
;   ret

function %store_with_constant_offset(i32, i32) {
block0(v0: i32, v1: i32):
  store.i32 v1, v0+8
  return
}

; VCode:
; block0:
;   sw a1,8(a0)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sw a1, 8(a0) ; trap: heap_oob
;   ret

