test compile precise-output
set unwind_info=false
target riscv32 has_m

function %iadd_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = iadd.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   add a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   add a0, a0, a1
;   ret

function %isub_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = isub.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   sub a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sub a0, a0, a1
;   ret

function %imul_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = imul.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   mul a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mul a0, a0, a1
;   ret

function %iconst_i32() -> i32 {
block0:
  v0 = iconst.i32 42
  return v0
}

; VCode:
; block0:
;   li a0,42
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi a0, zero, 0x2a
;   ret

