test compile precise-output
set unwind_info=false
target riscv32 has_m

function %call_indirect_i32(i32, i32) -> i32 {
    sig0 = (i32) -> i32
block0(v0: i32, v1: i32):
    v2 = call_indirect.i32 sig0, v1(v0)
    return v2
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   callind a1
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x11, 0x00
;   .byte 0x23, 0x30, 0x81, 0x00
;   mv s0, sp
; block1: ; offset 0x10
;   jalr a1
;   .byte 0x83, 0x30, 0x81, 0x00
;   .byte 0x03, 0x34, 0x01, 0x00
;   addi sp, sp, 0x10
;   ret

