test compile precise-output
set enable_multi_ret_implicit_sret
set unwind_info=false
target riscv32 has_m

function %call_i32(i32) -> i32 {
    fn0 = %g(i32) -> i32

block0(v0: i32):
    v1 = call fn0(v0)
    return v1
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   load_ext_name_far a3,%g+0
;   callind a3
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x11, 0x00
;   .byte 0x23, 0x30, 0x81, 0x00
;   mv s0, sp
; block1: ; offset 0x10
;   auipc a3, 0
;   .byte 0x83, 0xb6, 0xc6, 0x00
;   j 0xc
;   .byte 0x00, 0x00, 0x00, 0x00 ; reloc_external Abs8 %g 0
;   .byte 0x00, 0x00, 0x00, 0x00
;   jalr a3
;   .byte 0x83, 0x30, 0x81, 0x00
;   .byte 0x03, 0x34, 0x01, 0x00
;   addi sp, sp, 0x10
;   ret

function %call_multi_arg(i32, i32, i32) -> i32 {
    fn0 = %add3(i32, i32, i32) -> i32

block0(v0: i32, v1: i32, v2: i32):
    v3 = call fn0(v0, v1, v2)
    return v3
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   load_ext_name_far a5,%add3+0
;   callind a5
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x11, 0x00
;   .byte 0x23, 0x30, 0x81, 0x00
;   mv s0, sp
; block1: ; offset 0x10
;   auipc a5, 0
;   .byte 0x83, 0xb7, 0xc7, 0x00
;   j 0xc
;   .byte 0x00, 0x00, 0x00, 0x00 ; reloc_external Abs8 %add3 0
;   .byte 0x00, 0x00, 0x00, 0x00
;   jalr a5
;   .byte 0x83, 0x30, 0x81, 0x00
;   .byte 0x03, 0x34, 0x01, 0x00
;   addi sp, sp, 0x10
;   ret

