test compile precise-output
set unwind_info=false
target riscv32 has_m

; Basic icmp and return
function %icmp_eq_i32(i32, i32) -> i8 {
block0(v0: i32, v1: i32):
  v2 = icmp eq v0, v1
  return v2
}

; VCode:
; block0:
;   slli a3,a0,32
;   srai a5,a3,32
;   slli a1,a1,32
;   srai a3,a1,32
;   xor a5,a5,a3
;   seqz a0,a5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a3, a0, 0x20
;   srai a5, a3, 0x20
;   slli a1, a1, 0x20
;   srai a3, a1, 0x20
;   xor a5, a5, a3
;   seqz a0, a5
;   ret

function %icmp_eq_brif_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = icmp eq v0, v1
  brif v2, block1, block2

block1:
  v4 = iconst.i32 1
  return v4

block2:
  v5 = iconst.i32 2
  return v5
}

; VCode:
; block0:
;   mv a3,a1
;   slli a5,a0,32
;   srai a1,a5,32
;   mv a5,a3
;   slli a3,a5,32
;   srai a5,a3,32
;   beq a1,a5,taken(label2),not_taken(label1)
; block1:
;   li a0,2
;   ret
; block2:
;   li a0,1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a3, a1
;   slli a5, a0, 0x20
;   srai a1, a5, 0x20
;   mv a5, a3
;   slli a3, a5, 0x20
;   srai a5, a3, 0x20
;   beq a1, a5, 0xc
; block1: ; offset 0x1c
;   addi a0, zero, 2
;   ret
; block2: ; offset 0x24
;   addi a0, zero, 1
;   ret

function %icmp_eq_brif_same_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = icmp eq v0, v1
  brif v2, block1, block1

block1:
  v4 = iconst.i32 1
  return v4
}

; VCode:
; block0:
;   slli a4,a0,32
;   srai a0,a4,32
;   slli a2,a1,32
;   srai a4,a2,32
;   beq a0,a4,taken(label1),not_taken(label2)
; block1:
;   j label3
; block2:
;   j label3
; block3:
;   li a0,1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a4, a0, 0x20
;   srai a0, a4, 0x20
;   slli a2, a1, 0x20
;   srai a4, a2, 0x20
; block1: ; offset 0x10
;   addi a0, zero, 1
;   ret

function %i8_brif(i8){
block0(v0: i8):
    brif v0, block1, block1

block1:
    nop
    return
}

; VCode:
; block0:
;   andi a2,a0,255
;   bne a2,zero,taken(label1),not_taken(label2)
; block1:
;   j label3
; block2:
;   j label3
; block3:
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a2, a0, 0xff
; block1: ; offset 0x4
;   ret

function %i16_brif(i16){
block0(v0: i16):
    brif v0, block1, block1

block1:
    nop
    return
}

; VCode:
; block0:
;   slli a2,a0,48
;   srai a4,a2,48
;   bne a4,zero,taken(label1),not_taken(label2)
; block1:
;   j label3
; block2:
;   j label3
; block3:
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a2, a0, 0x30
;   srai a4, a2, 0x30
; block1: ; offset 0x8
;   ret

function %i32_brif(i32){
block0(v0: i32):
    brif v0, block1, block1

block1:
    nop
    return
}

; VCode:
; block0:
;   slli a2,a0,32
;   srai a4,a2,32
;   bne a4,zero,taken(label1),not_taken(label2)
; block1:
;   j label3
; block2:
;   j label3
; block3:
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a2, a0, 0x20
;   srai a4, a2, 0x20
; block1: ; offset 0x8
;   ret

