test compile precise-output
set unwind_info=false
target riscv32 has_m

function %iconst_i8_m1() -> i8 {
block0:
  v0 = iconst.i8 -1
  return v0
}

; VCode:
; block0:
;   li a0,-1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi a0, zero, -1
;   ret

function %iconst_i16_zero() -> i16 {
block0:
  v0 = iconst.i16 0
  return v0
}

; VCode:
; block0:
;   li a0,0
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a0, zero
;   ret

function %iconst_i32_zero() -> i32 {
block0:
  v0 = iconst.i32 0
  return v0
}

; VCode:
; block0:
;   li a0,0
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a0, zero
;   ret

function %iconst_i32_small() -> i32 {
block0:
  v0 = iconst.i32 0xffff
  return v0
}

; VCode:
; block0:
;   lui a0,16
;   addi a0,a0,-1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lui a0, 0x10
;   addi a0, a0, -1
;   ret

function %iconst_i32_upper() -> i32 {
block0:
  v0 = iconst.i32 0xffff0000
  return v0
}

; VCode:
; block0:
;   lui a0,-16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lui a0, 0xffff0
;   ret

function %iconst_i32_max() -> i32 {
block0:
  v0 = iconst.i32 0xffffffff
  return v0
}

; VCode:
; block0:
;   li a0,-1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi a0, zero, -1
;   ret

function %iconst_i32_42() -> i32 {
block0:
  v0 = iconst.i32 42
  return v0
}

; VCode:
; block0:
;   li a0,42
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi a0, zero, 0x2a
;   ret

function %iconst_i32_2048() -> i32 {
block0:
  v0 = iconst.i32 2048
  return v0
}

; VCode:
; block0:
;   lui a0,1
;   addi a0,a0,-2048
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lui a0, 1
;   addi a0, a0, -0x800
;   ret

function %iconst_i32_large() -> i32 {
block0:
  v0 = iconst.i32 0x12345678
  return v0
}

; VCode:
; block0:
;   lui a0,74565
;   addi a0,a0,1656
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lui a0, 0x12345
;   addi a0, a0, 0x678
;   ret

