test compile precise-output
set unwind_info=false
target riscv32 has_m

function %ishl_i8_i8(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a3,a1,7
;   sll a0,a0,a3
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a3, a1, 7
;   sll a0, a0, a3
;   ret

function %ishl_i16_i16(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a3,a1,15
;   sll a0,a0,a3
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a3, a1, 0xf
;   sll a0, a0, a3
;   ret

function %ishl_i32_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   sll a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sll a0, a0, a1
;   ret

function %ishl_i32_imm(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 17
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   slli a0,a0,17
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a0, a0, 0x11
;   ret

;;;; i64 tests (2-register pattern on RV32)

function %ishl_i64_i8(i64, i8) -> i64 {
block0(v0: i64, v1: i8):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a5,a2,31
;   li a3,32
;   sub a3,a3,a5
;   sll a4,a0,a5
;   srl a0,a0,a3
;   select a3,zero,a0##condition=(a5 eq zero)
;   sll a5,a1,a5
;   or t0,a3,a5
;   li a3,32
;   andi a5,a2,63
;   select [a0,a1],[zero,a4],[a4,t0]##condition=(a5 uge a3)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a5, a2, 0x1f
;   addi a3, zero, 0x20
;   sub a3, a3, a5
;   sll a4, a0, a5
;   srl a0, a0, a3
;   mv a3, zero
;   beqz a5, 8
;   mv a3, a0
;   sll a5, a1, a5
;   or t0, a3, a5
;   addi a3, zero, 0x20
;   andi a5, a2, 0x3f
;   mv a0, zero
;   mv a1, a4
;   bgeu a5, a3, 0xc
;   mv a0, a4
;   mv a1, t0
;   ret

function %ishl_i64_i16(i64, i16) -> i64 {
block0(v0: i64, v1: i16):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a5,a2,31
;   li a3,32
;   sub a3,a3,a5
;   sll a4,a0,a5
;   srl a0,a0,a3
;   select a3,zero,a0##condition=(a5 eq zero)
;   sll a5,a1,a5
;   or t0,a3,a5
;   li a3,32
;   andi a5,a2,63
;   select [a0,a1],[zero,a4],[a4,t0]##condition=(a5 uge a3)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a5, a2, 0x1f
;   addi a3, zero, 0x20
;   sub a3, a3, a5
;   sll a4, a0, a5
;   srl a0, a0, a3
;   mv a3, zero
;   beqz a5, 8
;   mv a3, a0
;   sll a5, a1, a5
;   or t0, a3, a5
;   addi a3, zero, 0x20
;   andi a5, a2, 0x3f
;   mv a0, zero
;   mv a1, a4
;   bgeu a5, a3, 0xc
;   mv a0, a4
;   mv a1, t0
;   ret

function %ishl_i64_i32(i64, i32) -> i64 {
block0(v0: i64, v1: i32):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a5,a2,31
;   li a3,32
;   sub a3,a3,a5
;   sll a4,a0,a5
;   srl a0,a0,a3
;   select a3,zero,a0##condition=(a5 eq zero)
;   sll a5,a1,a5
;   or t0,a3,a5
;   li a3,32
;   andi a5,a2,63
;   select [a0,a1],[zero,a4],[a4,t0]##condition=(a5 uge a3)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a5, a2, 0x1f
;   addi a3, zero, 0x20
;   sub a3, a3, a5
;   sll a4, a0, a5
;   srl a0, a0, a3
;   mv a3, zero
;   beqz a5, 8
;   mv a3, a0
;   sll a5, a1, a5
;   or t0, a3, a5
;   addi a3, zero, 0x20
;   andi a5, a2, 0x3f
;   mv a0, zero
;   mv a1, a4
;   bgeu a5, a3, 0xc
;   mv a0, a4
;   mv a1, t0
;   ret

function %ishl_i64_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   mv a5,a0
;   andi a0,a2,31
;   li a3,32
;   sub a3,a3,a0
;   mv a4,a5
;   sll a5,a4,a0
;   srl a3,a4,a3
;   select a3,zero,a3##condition=(a0 eq zero)
;   sll a0,a1,a0
;   or a4,a3,a0
;   li a3,32
;   andi a2,a2,63
;   select [a0,a1],[zero,a5],[a5,a4]##condition=(a2 uge a3)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a5, a0
;   andi a0, a2, 0x1f
;   addi a3, zero, 0x20
;   sub a3, a3, a0
;   mv a4, a5
;   sll a5, a4, a0
;   srl a3, a4, a3
;   bnez a0, 8
;   mv a3, zero
;   sll a0, a1, a0
;   or a4, a3, a0
;   addi a3, zero, 0x20
;   andi a2, a2, 0x3f
;   mv a0, zero
;   mv a1, a5
;   bgeu a2, a3, 0xc
;   mv a0, a5
;   mv a1, a4
;   ret

function %ishl_i64_imm(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 17
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   li a3,17
;   li a5,0
;   andi a2,a3,31
;   li a4,32
;   sub a4,a4,a2
;   sll a5,a0,a2
;   srl a4,a0,a4
;   select a4,zero,a4##condition=(a2 eq zero)
;   sll a0,a1,a2
;   or a2,a4,a0
;   li a4,32
;   andi a3,a3,63
;   select [a0,a1],[zero,a5],[a5,a2]##condition=(a3 uge a4)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi a3, zero, 0x11
;   mv a5, zero
;   andi a2, a3, 0x1f
;   addi a4, zero, 0x20
;   sub a4, a4, a2
;   sll a5, a0, a2
;   srl a4, a0, a4
;   bnez a2, 8
;   mv a4, zero
;   sll a0, a1, a2
;   or a2, a4, a0
;   addi a4, zero, 0x20
;   andi a3, a3, 0x3f
;   mv a0, zero
;   mv a1, a5
;   bgeu a3, a4, 0xc
;   mv a0, a5
;   mv a1, a2
;   ret

function %ishl_i64_imm_32(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 32
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   li a3,32
;   li a5,0
;   andi a2,a3,31
;   li a4,32
;   sub a4,a4,a2
;   sll a5,a0,a2
;   srl a4,a0,a4
;   select a4,zero,a4##condition=(a2 eq zero)
;   sll a0,a1,a2
;   or a2,a4,a0
;   li a4,32
;   andi a3,a3,63
;   select [a0,a1],[zero,a5],[a5,a2]##condition=(a3 uge a4)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi a3, zero, 0x20
;   mv a5, zero
;   andi a2, a3, 0x1f
;   addi a4, zero, 0x20
;   sub a4, a4, a2
;   sll a5, a0, a2
;   srl a4, a0, a4
;   bnez a2, 8
;   mv a4, zero
;   sll a0, a1, a2
;   or a2, a4, a0
;   addi a4, zero, 0x20
;   andi a3, a3, 0x3f
;   mv a0, zero
;   mv a1, a5
;   bgeu a3, a4, 0xc
;   mv a0, a5
;   mv a1, a2
;   ret

function %ishl_i64_imm_63(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 63
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   li a3,63
;   li a5,0
;   andi a2,a3,31
;   li a4,32
;   sub a4,a4,a2
;   sll a5,a0,a2
;   srl a4,a0,a4
;   select a4,zero,a4##condition=(a2 eq zero)
;   sll a0,a1,a2
;   or a2,a4,a0
;   li a4,32
;   andi a3,a3,63
;   select [a0,a1],[zero,a5],[a5,a2]##condition=(a3 uge a4)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi a3, zero, 0x3f
;   mv a5, zero
;   andi a2, a3, 0x1f
;   addi a4, zero, 0x20
;   sub a4, a4, a2
;   sll a5, a0, a2
;   srl a4, a0, a4
;   bnez a2, 8
;   mv a4, zero
;   sll a0, a1, a2
;   or a2, a4, a0
;   addi a4, zero, 0x20
;   andi a3, a3, 0x3f
;   mv a0, zero
;   mv a1, a5
;   bgeu a3, a4, 0xc
;   mv a0, a5
;   mv a1, a2
;   ret

