test compile precise-output
set unwind_info=false
target riscv32 has_m

function %load_uextend_i8_i16(i32) -> i16 {
block0(v0: i32):
  v1 = load.i8 v0
  v2 = uextend.i16 v1
  return v2
}

; VCode:
; block0:
;   lbu a0,0(a0)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lbu a0, 0(a0) ; trap: heap_oob
;   ret

function %load_uextend_i8_i32(i32) -> i32 {
block0(v0: i32):
  v1 = load.i8 v0
  v2 = uextend.i32 v1
  return v2
}

; VCode:
; block0:
;   lbu a0,0(a0)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lbu a0, 0(a0) ; trap: heap_oob
;   ret

function %load_uextend_i16_i32(i32) -> i32 {
block0(v0: i32):
  v1 = load.i16 v0
  v2 = uextend.i32 v1
  return v2
}

; VCode:
; block0:
;   lhu a0,0(a0)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lhu a0, 0(a0) ; trap: heap_oob
;   ret

function %load_sextend_i8_i16(i32) -> i16 {
block0(v0: i32):
  v1 = load.i8 v0
  v2 = sextend.i16 v1
  return v2
}

; VCode:
; block0:
;   lb a0,0(a0)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lb a0, 0(a0) ; trap: heap_oob
;   ret

function %load_sextend_i8_i32(i32) -> i32 {
block0(v0: i32):
  v1 = load.i8 v0
  v2 = sextend.i32 v1
  return v2
}

; VCode:
; block0:
;   lb a0,0(a0)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lb a0, 0(a0) ; trap: heap_oob
;   ret

function %load_sextend_i16_i32(i32) -> i32 {
block0(v0: i32):
  v1 = load.i16 v0
  v2 = sextend.i32 v1
  return v2
}

; VCode:
; block0:
;   lh a0,0(a0)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lh a0, 0(a0) ; trap: heap_oob
;   ret

