test compile precise-output
set unwind_info=false
target riscv32 has_m

function %simple() -> i32 {
block0:
  v0 = iconst.i32 123
  return v0
}

; VCode:
; block0:
;   li a0,123
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi a0, zero, 0x7b
;   ret

function %with_call() -> i32 {
    fn0 = %helper() -> i32

block0:
  v0 = call fn0()
  return v0
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   load_ext_name_far a1,%helper+0
;   callind a1
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x11, 0x00
;   .byte 0x23, 0x30, 0x81, 0x00
;   mv s0, sp
; block1: ; offset 0x10
;   auipc a1, 0
;   .byte 0x83, 0xb5, 0xc5, 0x00
;   j 0xc
;   .byte 0x00, 0x00, 0x00, 0x00 ; reloc_external Abs8 %helper 0
;   .byte 0x00, 0x00, 0x00, 0x00
;   jalr a1
;   .byte 0x83, 0x30, 0x81, 0x00
;   .byte 0x03, 0x34, 0x01, 0x00
;   addi sp, sp, 0x10
;   ret

