test compile precise-output
set unwind_info=false
target riscv32 has_m

function %rotr_i32_const(i32) -> i32 {
block0(v0: i32):
  v1 = iconst.i32 5
  v2 = rotr.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   li a1,5
;   slli a3,a0,32
;   srli a5,a3,32
;   andi a1,a1,31
;   li a3,32
;   sub a0,a3,a1
;   srl a2,a5,a1
;   sll a3,a5,a0
;   select a5,zero,a3##condition=(a1 eq zero)
;   or a0,a2,a5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi a1, zero, 5
;   slli a3, a0, 0x20
;   srli a5, a3, 0x20
;   andi a1, a1, 0x1f
;   addi a3, zero, 0x20
;   sub a0, a3, a1
;   srl a2, a5, a1
;   sll a3, a5, a0
;   mv a5, zero
;   beqz a1, 8
;   mv a5, a3
;   or a0, a2, a5
;   ret

;;;; i64 tests (2-register pattern on RV32)

function %rotr_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
  v2 = rotr.i64 v0, v1
  return v2
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-16
;   sd s10,8(sp)
; block0:
;   andi a5,a2,31
;   li a2,32
;   sub a3,a2,a5
;   srl a2,a0,a5
;   mv s10,a0
;   sll a4,a1,a3
;   select a4,zero,a4##condition=(a5 eq zero)
;   or a0,a2,a4
;   srl a1,a1,a5
;   mv a2,s10
;   sll a3,a2,a3
;   select a2,zero,a3##condition=(a5 eq zero)
;   or a1,a1,a2
;   ld s10,8(sp)
;   addi sp,sp,16
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x11, 0x00
;   .byte 0x23, 0x30, 0x81, 0x00
;   mv s0, sp
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0xa1, 0x01
; block1: ; offset 0x18
;   andi a5, a2, 0x1f
;   addi a2, zero, 0x20
;   sub a3, a2, a5
;   srl a2, a0, a5
;   mv s10, a0
;   sll a4, a1, a3
;   bnez a5, 8
;   mv a4, zero
;   or a0, a2, a4
;   srl a1, a1, a5
;   mv a2, s10
;   sll a3, a2, a3
;   mv a2, zero
;   beqz a5, 8
;   mv a2, a3
;   or a1, a1, a2
;   .byte 0x03, 0x3d, 0x81, 0x00
;   addi sp, sp, 0x10
;   .byte 0x83, 0x30, 0x81, 0x00
;   .byte 0x03, 0x34, 0x01, 0x00
;   addi sp, sp, 0x10
;   ret

function %rotr_i64_const(i64) -> i64 {
block0(v0: i64):
  v1 = iconst.i64 5
  v2 = rotr.i64 v0, v1
  return v2
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-16
;   sd s10,8(sp)
; block0:
;   li a2,5
;   li a4,0
;   andi a5,a2,31
;   li a2,32
;   sub a3,a2,a5
;   srl a2,a0,a5
;   mv s10,a0
;   sll a4,a1,a3
;   select a4,zero,a4##condition=(a5 eq zero)
;   or a0,a2,a4
;   srl a1,a1,a5
;   mv a2,s10
;   sll a3,a2,a3
;   select a2,zero,a3##condition=(a5 eq zero)
;   or a1,a1,a2
;   ld s10,8(sp)
;   addi sp,sp,16
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x11, 0x00
;   .byte 0x23, 0x30, 0x81, 0x00
;   mv s0, sp
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0xa1, 0x01
; block1: ; offset 0x18
;   addi a2, zero, 5
;   mv a4, zero
;   andi a5, a2, 0x1f
;   addi a2, zero, 0x20
;   sub a3, a2, a5
;   srl a2, a0, a5
;   mv s10, a0
;   sll a4, a1, a3
;   bnez a5, 8
;   mv a4, zero
;   or a0, a2, a4
;   srl a1, a1, a5
;   mv a2, s10
;   sll a3, a2, a3
;   mv a2, zero
;   beqz a5, 8
;   mv a2, a3
;   or a1, a1, a2
;   .byte 0x03, 0x3d, 0x81, 0x00
;   addi sp, sp, 0x10
;   .byte 0x83, 0x30, 0x81, 0x00
;   .byte 0x03, 0x34, 0x01, 0x00
;   addi sp, sp, 0x10
;   ret

function %rotr_i64_const_i32(i64) -> i64 {
block0(v0: i64):
  v1 = iconst.i32 5
  v2 = rotr.i64 v0, v1
  return v2
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-16
;   sd s9,8(sp)
; block0:
;   li a2,5
;   andi a4,a2,31
;   li a2,32
;   sub a2,a2,a4
;   srl a5,a0,a4
;   mv s9,a0
;   sll a0,a1,a2
;   select a3,zero,a0##condition=(a4 eq zero)
;   or a0,a5,a3
;   srl a1,a1,a4
;   mv a3,s9
;   sll a2,a3,a2
;   select a5,zero,a2##condition=(a4 eq zero)
;   or a1,a1,a5
;   ld s9,8(sp)
;   addi sp,sp,16
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x11, 0x00
;   .byte 0x23, 0x30, 0x81, 0x00
;   mv s0, sp
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x91, 0x01
; block1: ; offset 0x18
;   addi a2, zero, 5
;   andi a4, a2, 0x1f
;   addi a2, zero, 0x20
;   sub a2, a2, a4
;   srl a5, a0, a4
;   mv s9, a0
;   sll a0, a1, a2
;   mv a3, zero
;   beqz a4, 8
;   mv a3, a0
;   or a0, a5, a3
;   srl a1, a1, a4
;   mv a3, s9
;   sll a2, a3, a2
;   mv a5, zero
;   beqz a4, 8
;   mv a5, a2
;   or a1, a1, a5
;   .byte 0x83, 0x3c, 0x81, 0x00
;   addi sp, sp, 0x10
;   .byte 0x83, 0x30, 0x81, 0x00
;   .byte 0x03, 0x34, 0x01, 0x00
;   addi sp, sp, 0x10
;   ret

function %rotr_i64_const_32(i64) -> i64 {
block0(v0: i64):
  v1 = iconst.i64 32
  v2 = rotr.i64 v0, v1
  return v2
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-16
;   sd s10,8(sp)
; block0:
;   li a2,32
;   li a4,0
;   andi a5,a2,31
;   li a2,32
;   sub a3,a2,a5
;   srl a2,a0,a5
;   mv s10,a0
;   sll a4,a1,a3
;   select a4,zero,a4##condition=(a5 eq zero)
;   or a0,a2,a4
;   srl a1,a1,a5
;   mv a2,s10
;   sll a3,a2,a3
;   select a2,zero,a3##condition=(a5 eq zero)
;   or a1,a1,a2
;   ld s10,8(sp)
;   addi sp,sp,16
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x11, 0x00
;   .byte 0x23, 0x30, 0x81, 0x00
;   mv s0, sp
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0xa1, 0x01
; block1: ; offset 0x18
;   addi a2, zero, 0x20
;   mv a4, zero
;   andi a5, a2, 0x1f
;   addi a2, zero, 0x20
;   sub a3, a2, a5
;   srl a2, a0, a5
;   mv s10, a0
;   sll a4, a1, a3
;   bnez a5, 8
;   mv a4, zero
;   or a0, a2, a4
;   srl a1, a1, a5
;   mv a2, s10
;   sll a3, a2, a3
;   mv a2, zero
;   beqz a5, 8
;   mv a2, a3
;   or a1, a1, a2
;   .byte 0x03, 0x3d, 0x81, 0x00
;   addi sp, sp, 0x10
;   .byte 0x83, 0x30, 0x81, 0x00
;   .byte 0x03, 0x34, 0x01, 0x00
;   addi sp, sp, 0x10
;   ret

