test compile precise-output
set unwind_info=false
set enable_probestack=true
target riscv32 has_m

function %stack_addr_small() -> i32 {
ss0 = explicit_slot 8

block0:
  v0 = stack_addr.i32 ss0
  return v0
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-16
; block0:
;   load_addr a0,0(slot)
;   addi sp,sp,16
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x11, 0x00
;   .byte 0x23, 0x30, 0x81, 0x00
;   mv s0, sp
;   addi sp, sp, -0x10
; block1: ; offset 0x14
;   mv a0, sp
;   addi sp, sp, 0x10
;   .byte 0x83, 0x30, 0x81, 0x00
;   .byte 0x03, 0x34, 0x01, 0x00
;   addi sp, sp, 0x10
;   ret

function %stack_load_small() -> i32 {
ss0 = explicit_slot 8

block0:
  v0 = stack_load.i32 ss0
  return v0
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-16
; block0:
;   lw a0,0(slot)
;   addi sp,sp,16
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x11, 0x00
;   .byte 0x23, 0x30, 0x81, 0x00
;   mv s0, sp
;   addi sp, sp, -0x10
; block1: ; offset 0x14
;   lw a0, 0(sp)
;   addi sp, sp, 0x10
;   .byte 0x83, 0x30, 0x81, 0x00
;   .byte 0x03, 0x34, 0x01, 0x00
;   addi sp, sp, 0x10
;   ret

function %stack_store_small(i32) {
ss0 = explicit_slot 8

block0(v0: i32):
  stack_store.i32 v0, ss0
  return
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-16
; block0:
;   sw a0,0(slot)
;   addi sp,sp,16
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   .byte 0x23, 0x34, 0x11, 0x00
;   .byte 0x23, 0x30, 0x81, 0x00
;   mv s0, sp
;   addi sp, sp, -0x10
; block1: ; offset 0x14
;   sw a0, 0(sp)
;   addi sp, sp, 0x10
;   .byte 0x83, 0x30, 0x81, 0x00
;   .byte 0x03, 0x34, 0x01, 0x00
;   addi sp, sp, 0x10
;   ret

