test interpret
test compile precise-output

set unwind_info=false
target riscv32 has_m

function %use_stack_slot() -> i32 {
ss0 = explicit_slot 16, align = 4

block0:
    v0 = iconst.i32 42
    stack_store v0, ss0
    v1 = stack_load.i32 ss0
    return v1
}

; VCode:
;   addi sp,sp,-8
;   sw ra,4(sp)
;   sw fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-16
; block0:
;   li a1,42
;   sw a1,0(slot)
;   lw a0,0(slot)
;   addi sp,sp,16
;   lw ra,4(sp)
;   lw fp,0(sp)
;   addi sp,sp,8
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -8
;   sw ra, 4(sp)
;   sw s0, 0(sp)
;   mv s0, sp
;   addi sp, sp, -0x10
; block1: ; offset 0x14
;   addi a1, zero, 0x2a
;   sw a1, 0(sp)
;   lw a0, 0(sp)
;   addi sp, sp, 0x10
;   lw ra, 4(sp)
;   lw s0, 0(sp)
;   addi sp, sp, 8
;   ret

