test compile precise-output

set unwind_info=false
target riscv32 has_m

function %add_4_args(i32, i32, i32, i32) -> i32 system_v {
block0(v0: i32, v1: i32, v2: i32, v3: i32):
    v16 = iadd v0, v1
    v17 = iadd v16, v2
    v18 = iadd v17, v3
    return v18
}

; VCode:
; block0:
;   add a1,a0,a1
;   add a1,a1,a2
;   add a0,a1,a3
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   add a1, a0, a1
;   add a1, a1, a2
;   add a0, a1, a3
;   ret

function %main() -> i32 system_v {
    fn0 = %add_4_args(i32, i32, i32, i32) -> i32
block0:
    v0 = iconst.i32 1
    v1 = iconst.i32 2
    v2 = iconst.i32 3
    v3 = iconst.i32 4
    v16 = call fn0(v0, v1, v2, v3)
    return v16
}

; VCode:
;   addi sp,sp,-8
;   sw ra,4(sp)
;   sw fp,0(sp)
;   mv fp,sp
; block0:
;   li a0,1
;   li a1,2
;   li a2,3
;   li a3,4
;   load_ext_name_far a5,%add_4_args+0
;   callind a5
;   lw ra,4(sp)
;   lw fp,0(sp)
;   addi sp,sp,8
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -8
;   sw ra, 4(sp)
;   sw s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   addi a0, zero, 1
;   addi a1, zero, 2
;   addi a2, zero, 3
;   addi a3, zero, 4
;   auipc a5, 0
;   lw a5, 0xc(a5)
;   j 8
;   .byte 0x00, 0x00, 0x00, 0x00 ; reloc_external Abs4 %add_4_args 0
;   jalr a5
;   lw ra, 4(sp)
;   lw s0, 0(sp)
;   addi sp, sp, 8
;   ret

